### ISSUE TITLE
Framerate limiter addition

### ISSUE THREAD

**Issue by Devorlon** [WallSoGB/FalloutNV-Performance-Guide#3]
I'm on my laptop right now so I can't make the PR myself, but DXVK has a built in frame limiter.

In dxvk.conf there's:

`# d3gi.maxFrameRate = 0`
`# d3d9.maxFrameRate = 0`

Removing the hash and setting the 0 to any non negiative value will limit the frame rate.

**Comment by WallSoGB** [comment]
DXVK limiter used to be in the guide, but has been removed due to issues (framerate dropping in interiors and other oddities). Also, it's not even that good.
